services:
  manager:
    image: manager
    build:
      context: ./ManagerProject
      dockerfile: ./Dockerfile
    environment:
        - SPRING_APPLICATION_JSON={"server.port":8080,"workers_url":"http://worker-1:8090 http://worker-2:8091 http://worker-3:8092 http://worker-4:8093 http://worker-5:8094 http://worker-6:8095 http://worker-7:8096 http://worker-8:8097"}
    ports:
      - "8080:8080"

  worker-1:
    image: worker
    build:
      context: ./WorkerProject
      dockerfile: ./Dockerfile
    environment:
        - SPRING_APPLICATION_JSON={"server.port":8090,"manager_url":"http://manager:8080"}

  worker-2:
    image: worker
    build:
      context: ./WorkerProject
      dockerfile: ./Dockerfile
    environment:
        - SPRING_APPLICATION_JSON={"server.port":8091,"manager_url":"http://manager:8080"}

  worker-3:
    image: worker
    build:
      context: ./WorkerProject
      dockerfile: ./Dockerfile
    environment:
        - SPRING_APPLICATION_JSON={"server.port":8092,"manager_url":"http://manager:8080"}

  worker-4:
    image: worker
    build:
      context: ./WorkerProject
      dockerfile: ./Dockerfile
    environment:
        - SPRING_APPLICATION_JSON={"server.port":8093,"manager_url":"http://manager:8080"}
      
  worker-5:
    image: worker
    build:
      context: ./WorkerProject
      dockerfile: ./Dockerfile
    environment:
        - SPRING_APPLICATION_JSON={"server.port":8094,"manager_url":"http://manager:8080"}

  worker-6:
    image: worker
    build:
      context: ./WorkerProject
      dockerfile: ./Dockerfile
    environment:
        - SPRING_APPLICATION_JSON={"server.port":8095,"manager_url":"http://manager:8080"}

  worker-7:
    image: worker
    build:
      context: ./WorkerProject
      dockerfile: ./Dockerfile
    environment:
        - SPRING_APPLICATION_JSON={"server.port":8096,"manager_url":"http://manager:8080"}

  worker-8:
    image: worker
    build:
      context: ./WorkerProject
      dockerfile: ./Dockerfile
    environment:
        - SPRING_APPLICATION_JSON={"server.port":8097,"manager_url":"http://manager:8080"}